//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


// Handy interface to encapsulate a view when it's type is unknown
public interface View{
	// Nothing to declare
}


// It can have non logical state, but the view must always reflect the current state of the model
public class View<T>:View where T:Model{
	
	// Visual update - frame rate dependant
	public virtual void Update(T model, float deltaTime){
		// Default view does nothing
	}

	// Helps identify if this view can be reused for other model
	// Incompatible if there are heavy resources that must be (re)load
	public virtual bool IsCompatible(T originalModel, T newModel){
		return true; // Default 
	}


	public virtual void OnDestroy(T model){
		// Nothing by default
	}
	
}