using System;
using System.Collections.Generic;
using ProtoBuf;


namespace RetroBread{


	// Comparer using keyframe order, if equal use player
	public class EventComparerByKeyframe:IComparer<Event>{
		
		int IComparer<Event>.Compare(Event event1, Event event2) {
			if (event1.Keyframe == event2.Keyframe){
				return event1.PlayerId.CompareTo(event2.PlayerId);
			}
			return event1.Keyframe.CompareTo(event2.Keyframe);
		}
		
	}


	// Represents a player action at a specific momment in the game
	[ProtoContract]
	[ProtoInclude(10, typeof(ButtonInputEvent))]
	[ProtoInclude(11, typeof(AxisInputEvent))]
	public abstract class Event{

		// An event happens in a specific key frame
		[ProtoMember(1)]
		public uint Keyframe { get; set; }

		// Events are always generated by players
		[ProtoMember(2)]
		public uint PlayerId { get; set; }


		// Default Constructor
		public Event(){
			// Nothing to do
		}
		

	}


}

