//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


// Plane model
[Serializable]
public class MovingPlaneModel: PhysicPlaneModel{

	public int movingState;

	// Constructor giving world points
	public MovingPlaneModel(int updatingOrder, params FixedVector3[] paramPoints):base(updatingOrder, paramPoints){
		// Nothing else to add
	}


	// Create controller
	protected override Controller<PhysicPlaneModel> CreateController(){
		return new MovingPlaneController();
	}

}

