//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

// Comparer using keyframe order, if equal use player
public class EventComparerByKeyframe:IComparer<Event>{
	
	int IComparer<Event>.Compare(Event event1, Event event2) {
		if (event1.Keyframe == event2.Keyframe){
			return event1.PlayerId.CompareTo(event2.PlayerId);
		}
		return event1.Keyframe.CompareTo(event2.Keyframe);
	}
	
}


// Represents a player action at a specific momment in the game
[Serializable]
public abstract class Event{

	// An event happens in a specific key frame
	public uint Keyframe { get; set; }

	// Events are always generated by players
	public uint PlayerId { get; set; }
	

}

